/**
 * Default palettes and themes — shipped with @silvery/ansi.
 */

import type { ColorScheme, Theme } from "./types.ts"

export const ansi16DarkTheme: Theme = {
  name: "dark-ansi16",
  bg: "",
  fg: "whiteBright",
  muted: "white",
  mutedbg: "black",
  surface: "whiteBright",
  surfacebg: "black",
  popover: "whiteBright",
  popoverbg: "black",
  inverse: "black",
  inversebg: "whiteBright",
  cursor: "black",
  cursorbg: "yellow",
  selection: "black",
  selectionbg: "yellow",
  primary: "yellow",
  primaryfg: "black",
  secondary: "white",
  secondaryfg: "black",
  accent: "blueBright",
  accentfg: "black",
  error: "redBright",
  errorfg: "black",
  warning: "yellow",
  warningfg: "black",
  success: "greenBright",
  successfg: "black",
  info: "cyan",
  infofg: "black",
  border: "gray",
  inputborder: "gray",
  focusborder: "blueBright",
  link: "blueBright",
  disabledfg: "gray",
  palette: [
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "magenta",
    "cyan",
    "white",
    "blackBright",
    "redBright",
    "greenBright",
    "yellowBright",
    "blueBright",
    "magentaBright",
    "cyanBright",
    "whiteBright",
  ],
}

export const ansi16LightTheme: Theme = {
  name: "light-ansi16",
  bg: "",
  fg: "black",
  muted: "blackBright",
  mutedbg: "white",
  surface: "black",
  surfacebg: "white",
  popover: "black",
  popoverbg: "white",
  inverse: "whiteBright",
  inversebg: "black",
  cursor: "black",
  cursorbg: "blue",
  selection: "black",
  selectionbg: "cyan",
  primary: "blue",
  primaryfg: "black",
  secondary: "blue",
  secondaryfg: "black",
  accent: "cyan",
  accentfg: "black",
  error: "red",
  errorfg: "black",
  warning: "yellow",
  warningfg: "black",
  success: "green",
  successfg: "black",
  info: "cyan",
  infofg: "black",
  border: "gray",
  inputborder: "gray",
  focusborder: "blue",
  link: "blueBright",
  disabledfg: "gray",
  palette: [
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "magenta",
    "cyan",
    "white",
    "blackBright",
    "redBright",
    "greenBright",
    "yellowBright",
    "blueBright",
    "magentaBright",
    "cyanBright",
    "whiteBright",
  ],
}

export const defaultDarkScheme: ColorScheme = {
  name: "default-dark",
  dark: true,
  black: "#2e3440",
  red: "#bf616a",
  green: "#a3be8c",
  yellow: "#ebcb8b",
  blue: "#81a1c1",
  magenta: "#b48ead",
  cyan: "#88c0d0",
  white: "#d8dee9",
  brightBlack: "#4c566a",
  brightRed: "#bf616a",
  brightGreen: "#a3be8c",
  brightYellow: "#ebcb8b",
  brightBlue: "#81a1c1",
  brightMagenta: "#b48ead",
  brightCyan: "#8fbcbb",
  brightWhite: "#eceff4",
  foreground: "#d8dee9",
  background: "#2e3440",
  cursorColor: "#d8dee9",
  cursorText: "#2e3440",
  selectionBackground: "#434c5e",
  selectionForeground: "#d8dee9",
}

export const defaultLightScheme: ColorScheme = {
  name: "default-light",
  dark: false,
  black: "#5c6370",
  red: "#d20f39",
  green: "#40a02b",
  yellow: "#df8e1d",
  blue: "#1e66f5",
  magenta: "#8839ef",
  cyan: "#179299",
  white: "#dce0e8",
  brightBlack: "#6c7086",
  brightRed: "#d20f39",
  brightGreen: "#40a02b",
  brightYellow: "#df8e1d",
  brightBlue: "#1e66f5",
  brightMagenta: "#8839ef",
  brightCyan: "#179299",
  brightWhite: "#eff1f5",
  foreground: "#4c4f69",
  background: "#eff1f5",
  cursorColor: "#dc8a78",
  cursorText: "#eff1f5",
  selectionBackground: "#ccd0da",
  selectionForeground: "#4c4f69",
}
