/**
 * Unified Web Viewer for Hightea Examples
 *
 * A DOM app (vanilla TypeScript, no React) that builds chrome around an xterm.js
 * terminal pane. Showcases run via renderToXterm() inside the terminal.
 *
 * Layout:
 *   Sidebar (220px) | Demo pane (flex) | Source pane (380px, collapsible)
 */

import { Terminal } from "@xterm/xterm"
import { FitAddon } from "@xterm/addon-fit"
import { renderToXterm } from "../../src/xterm/index.js"
import { SHOWCASES, emitInput, setTermFocused } from "./showcases.js"
import React from "react"

// =============================================================================
// Types
// =============================================================================

interface DemoEntry {
  id: string
  name: string
  description: string
  category: string
  features: string[]
  source: string
  component?: () => JSX.Element
}

interface Category {
  name: string
  color: string
  items: DemoEntry[]
}

// =============================================================================
// Registry
// =============================================================================

// Build registry from showcase components + metadata.
// The viewer-registry.js (generated by build) will eventually provide this;
// for now we define it inline from the showcases.

interface DemoMeta {
  name: string
  description: string
  category: string
  features: string[]
  source: string
}

const DEMO_METADATA: Record<string, DemoMeta> = {
  dashboard: {
    name: "System Dashboard",
    description: "Real-time metrics, service status, and event feed with live updating data.",
    category: "Showcases",
    features: ["Box", "Text", "borderStyle", "flexDirection", "useInput", "useEffect", "setInterval"],
    source: `import React, { useState, useEffect } from "react"
import { Box, Text, useInput } from "@hightea/term"

function DashboardShowcase() {
  const [tick, setTick] = useState(0)
  const [activePanel, setActivePanel] = useState(0)

  useEffect(() => {
    const id = setInterval(() => setTick((t) => t + 1), 1500)
    return () => clearInterval(id)
  }, [])

  useInput((_input, key) => {
    if (key.leftArrow) setActivePanel((p) => Math.max(0, p - 1))
    if (key.rightArrow) setActivePanel((p) => Math.min(2, p + 1))
  })

  const cpu = 28 + ((tick * 7) % 45)
  const metrics = [
    { label: "CPU", value: cpu, color: cpu > 60 ? "red" : "green" },
    { label: "Memory", value: 52 + ((tick * 5) % 30), color: "yellow" },
  ]

  return (
    <Box flexDirection="column" padding={1}>
      <Box flexDirection="row" gap={1}>
        <Box flexGrow={1} borderStyle="single"
             borderColor={activePanel === 0 ? "cyan" : "#444"}>
          <Text bold color="cyan">Metrics</Text>
          {metrics.map((m) => (
            <Box key={m.label} flexDirection="row" gap={1}>
              <Text>{m.label}</Text>
              <Text color={m.color}>
                {"━".repeat(Math.round(m.value / 5))}
              </Text>
              <Text bold color={m.color}>{m.value}%</Text>
            </Box>
          ))}
        </Box>
      </Box>
    </Box>
  )
}`,
  },
  "coding-agent": {
    name: "Coding Agent",
    description: "Claude Code-style coding agent with tool calls, code diffs, and streaming output.",
    category: "Showcases",
    features: ["Box", "Text", "outlineStyle", "flexDirection", "wrap"],
    source: `import React from "react"
import { Box, Text } from "@hightea/term"

function ToolBlock({ tool, label, children }) {
  const color = tool === "Read" ? "#89b4fa"
    : tool === "Edit" ? "#f9e2af" : "#a6e3a1"
  return (
    <Box outlineStyle="round" outlineColor="#45475a"
         flexDirection="column" paddingX={1} marginLeft={2}>
      <Text bold color={color}>{tool}</Text>
      <Text dim>{label}</Text>
      {children}
    </Box>
  )
}

function CodingAgent() {
  return (
    <Box flexDirection="column" padding={1}>
      <Text bold color="#cba6f7">● claude</Text>
      <Box paddingX={1}>
        <Text color="#cba6f7" bold>❯ </Text>
        <Text>Fix the login bug</Text>
      </Box>
      <ToolBlock tool="Read" label="src/auth.ts">
        <Text color="#a6adc8">48│ if (token.expired) return null</Text>
      </ToolBlock>
      <ToolBlock tool="Edit" label="src/auth.ts">
        <Text color="#f38ba8">- if (token.expired) return null</Text>
        <Text color="#a6e3a1">+ if (token.expired) return refreshToken(token)</Text>
      </ToolBlock>
      <Text color="#a6adc8">Fixed! All tests pass.</Text>
    </Box>
  )
}`,
  },
  kanban: {
    name: "Kanban Board",
    description: "Three-column kanban with selectable cards and tag badges.",
    category: "Showcases",
    features: ["Box", "Text", "borderStyle", "flexGrow", "useInput", "useState"],
    source: `import React, { useState } from "react"
import { Box, Text, useInput } from "@hightea/term"

const COLUMNS = [
  { title: "To Do", color: "red", cards: [
    { title: "Design landing page", tag: "design" },
    { title: "Write API docs", tag: "docs" },
  ]},
  { title: "In Progress", color: "yellow", cards: [
    { title: "User authentication", tag: "backend" },
    { title: "Dashboard redesign", tag: "frontend" },
  ]},
  { title: "Done", color: "green", cards: [
    { title: "Project setup", tag: "devops" },
    { title: "CI/CD pipeline", tag: "devops" },
  ]},
]

function KanbanShowcase() {
  const [col, setCol] = useState(0)
  const [card, setCard] = useState(0)

  useInput((_input, key) => {
    if (key.leftArrow) { setCol((c) => Math.max(0, c - 1)); setCard(0) }
    if (key.rightArrow) { setCol((c) => Math.min(2, c + 1)); setCard(0) }
    if (key.upArrow) setCard((c) => Math.max(0, c - 1))
    if (key.downArrow) setCard((c) => Math.min(2, c + 1))
  })

  return (
    <Box flexDirection="row" gap={1} padding={1}>
      {COLUMNS.map((column, ci) => (
        <Box key={ci} flexGrow={1} borderStyle="single"
             borderColor={ci === col ? "cyan" : "#444"}>
          <Text bold color={column.color}>{column.title}</Text>
          {column.cards.map((c, i) => (
            <Text key={i} bold={ci === col && i === card}
                  color={ci === col && i === card ? "cyan" : "white"}>
              {ci === col && i === card ? "▸ " : "  "}{c.title}
            </Text>
          ))}
        </Box>
      ))}
    </Box>
  )
}`,
  },
  "cli-wizard": {
    name: "CLI Wizard",
    description: "Clack-style interactive setup wizard with step-by-step progression.",
    category: "Showcases",
    features: ["Box", "Text", "useInput", "useState", "Fragment"],
    source: `import React, { useState } from "react"
import { Box, Text, useInput } from "@hightea/term"

const STEPS = [
  { label: "Project name", type: "text", answer: "my-app" },
  { label: "Framework", type: "select",
    options: ["Vanilla", "React", "Vue", "Svelte"] },
  { label: "TypeScript?", type: "select", options: ["Yes", "No"] },
  { label: "Package manager", type: "select",
    options: ["bun", "npm", "yarn", "pnpm"] },
]

function CLIWizardShowcase() {
  const [step, setStep] = useState(0)
  const [cursor, setCursor] = useState(0)

  useInput((_input, key) => {
    const current = STEPS[step]
    if (current?.type === "select") {
      if (key.upArrow) setCursor((c) => Math.max(0, c - 1))
      if (key.downArrow)
        setCursor((c) => Math.min(current.options!.length - 1, c + 1))
    }
    if (key.return && step < STEPS.length) {
      setStep((s) => s + 1)
      setCursor(0)
    }
  })

  return (
    <Box flexDirection="column" padding={1} paddingLeft={2}>
      <Text bold color="cyan">┌  create-app</Text>
      {STEPS.map((ws, i) => (
        <React.Fragment key={i}>
          <Text>
            <Text color={i < step ? "green" : i === step ? "cyan" : "#666"}>
              {i < step ? "◇" : i === step ? "◆" : "○"}
            </Text>
            <Text bold={i === step}>  {ws.label}</Text>
          </Text>
        </React.Fragment>
      ))}
    </Box>
  )
}`,
  },
  "data-explorer": {
    name: "Process Explorer",
    description: "Sortable data table with live CPU jitter and row selection.",
    category: "Showcases",
    features: ["Box", "Text", "backgroundColor", "flexDirection", "useInput", "useEffect"],
    source: `import React, { useState, useEffect } from "react"
import { Box, Text, useInput } from "@hightea/term"

const PROCESSES = [
  { id: "1024", name: "web-server", status: "running", cpu: 67 },
  { id: "1025", name: "db-primary", status: "running", cpu: 54 },
  { id: "1026", name: "api-gateway", status: "running", cpu: 48 },
  { id: "1027", name: "worker-pool", status: "running", cpu: 35 },
  { id: "1028", name: "cache-redis", status: "running", cpu: 22 },
]

function DataExplorerShowcase() {
  const [tick, setTick] = useState(0)
  const [selected, setSelected] = useState(0)

  useEffect(() => {
    const id = setInterval(() => setTick((t) => t + 1), 2000)
    return () => clearInterval(id)
  }, [])

  useInput((_input, key) => {
    if (key.upArrow) setSelected((r) => Math.max(0, r - 1))
    if (key.downArrow) setSelected((r) => Math.min(4, r + 1))
  })

  return (
    <Box flexDirection="column" padding={1}>
      <Text bold>Process Explorer</Text>
      <Box flexDirection="row" backgroundColor="#334">
        <Box width={6}><Text bold>ID</Text></Box>
        <Box width={15}><Text bold>Name</Text></Box>
        <Box width={6}><Text bold>CPU%</Text></Box>
      </Box>
      {PROCESSES.map((row, i) => (
        <Box key={row.id} flexDirection="row"
             backgroundColor={i === selected ? "#2a2a4e" : undefined}>
          <Box width={6}><Text color="#999">{row.id}</Text></Box>
          <Box width={15}><Text>{row.name}</Text></Box>
          <Box width={6}>
            <Text bold color={row.cpu > 50 ? "red" : "green"}>
              {row.cpu + ((tick * 7 + row.cpu) % 13) - 6}
            </Text>
          </Box>
        </Box>
      ))}
    </Box>
  )
}`,
  },
  "dev-tools": {
    name: "Log Viewer",
    description: "Filterable log viewer with live search, scroll, and level coloring.",
    category: "Showcases",
    features: ["Box", "Text", "borderStyle", "useInput", "useState", "wrap"],
    source: `import React, { useState } from "react"
import { Box, Text, useInput } from "@hightea/term"

const LOGS = [
  { time: "14:23:01", level: "INFO", message: "Server started on port 3000" },
  { time: "14:23:08", level: "WARN", message: "Cache miss ratio above threshold" },
  { time: "14:23:12", level: "ERROR", message: "Failed to connect to Redis" },
  { time: "14:23:15", level: "INFO", message: "Retry succeeded: Redis connected" },
]

function DevToolsShowcase() {
  const [query, setQuery] = useState("")

  useInput((input, key) => {
    if (input) setQuery((q) => q + input)
    if (key.backspace) setQuery((q) => q.slice(0, -1))
    if (key.escape) setQuery("")
  })

  const levelColor = (level: string) =>
    level === "INFO" ? "green" :
    level === "WARN" ? "yellow" :
    level === "ERROR" ? "red" : "blue"

  const filtered = query
    ? LOGS.filter((l) => l.message.toLowerCase().includes(query))
    : LOGS

  return (
    <Box flexDirection="column" padding={1}>
      <Box borderStyle="round" borderColor="cyan" paddingX={1}>
        <Text bold color="cyan">/ </Text>
        <Text>{query}</Text>
        <Text color="cyan">|</Text>
      </Box>
      {filtered.map((log, i) => (
        <Box key={i} flexDirection="row" gap={1}>
          <Text color="#888">{log.time}</Text>
          <Text bold color={levelColor(log.level)}>{log.level}</Text>
          <Text wrap="truncate">{log.message}</Text>
        </Box>
      ))}
    </Box>
  )
}`,
  },
  scroll: {
    name: "Scroll List",
    description: "Basic scrollable list with keyboard navigation.",
    category: "Showcases",
    features: ["Box", "Text", "borderStyle", "useInput"],
    source: `import React, { useState } from "react"
import { Box, Text, useInput } from "@hightea/term"

function ScrollShowcase() {
  const [scrollPos, setScrollPos] = useState(0)

  useInput((_input, key) => {
    if (key.upArrow) setScrollPos((p) => Math.max(0, p - 1))
    if (key.downArrow) setScrollPos((p) => Math.min(20, p + 1))
  })

  const items = Array.from({ length: 30 }, (_, i) => \`Item \${i + 1}\`)
  const visible = items.slice(scrollPos, scrollPos + 10)

  return (
    <Box flexDirection="column" padding={1}>
      <Box flexDirection="column" borderStyle="single" borderColor="#444">
        {visible.map((item, i) => (
          <Box key={scrollPos + i} paddingX={1}>
            <Text bold={i === 0} color={i === 0 ? "cyan" : "white"}>
              {item}
            </Text>
          </Box>
        ))}
      </Box>
    </Box>
  )
}`,
  },
  "layout-feedback": {
    name: "Layout Feedback",
    description: "Live display of content dimensions via useContentRect().",
    category: "Showcases",
    features: ["Box", "Text", "useContentRect", "justifyContent", "alignItems"],
    source: `import React from "react"
import { Box, Text, useContentRect } from "@hightea/term"

function LayoutFeedbackShowcase() {
  const { width, height } = useContentRect()

  return (
    <Box flexDirection="column" padding={1}>
      <Box
        flexDirection="column"
        borderStyle="single"
        borderColor="cyan"
        flexGrow={1}
        justifyContent="center"
        alignItems="center"
      >
        <Text>Width: {width}  Height: {height}</Text>
      </Box>
    </Box>
  )
}`,
  },
  focus: {
    name: "Focus Panels",
    description: "Tab-cycling focus across three panels.",
    category: "Showcases",
    features: ["Box", "Text", "borderStyle", "useInput"],
    source: `import React, { useState } from "react"
import { Box, Text, useInput } from "@hightea/term"

function FocusShowcase() {
  const [focused, setFocused] = useState(0)

  useInput((_input, key) => {
    if (key.tab) setFocused((p) => (p + 1) % 3)
  })

  const labels = ["Panel A", "Panel B", "Panel C"]

  return (
    <Box flexDirection="column" padding={1}>
      <Box flexDirection="row" gap={1}>
        {labels.map((label, i) => (
          <Box key={label} flexGrow={1}
               borderStyle="single"
               borderColor={i === focused ? "cyan" : "#444"}
               paddingX={1} paddingY={1}>
            <Text bold color={i === focused ? "cyan" : "white"}>
              {label}
            </Text>
            <Text color={i === focused ? "cyan" : "#666"}>
              {i === focused ? "● focused" : "○"}
            </Text>
          </Box>
        ))}
      </Box>
    </Box>
  )
}`,
  },
  "text-input": {
    name: "Text Input",
    description: "Live text echo with cursor, backspace, and clear.",
    category: "Showcases",
    features: ["Box", "Text", "borderStyle", "useInput"],
    source: `import React, { useState } from "react"
import { Box, Text, useInput } from "@hightea/term"

function TextInputShowcase() {
  const [text, setText] = useState("")

  useInput((input, key) => {
    if (input) setText((t) => t + input)
    if (key.backspace) setText((t) => t.slice(0, -1))
    if (key.escape) setText("")
  })

  return (
    <Box flexDirection="column" padding={1}>
      <Box borderStyle="single" borderColor="#444" paddingX={1}>
        <Text>&gt; </Text>
        <Text>{text}</Text>
        <Text color="cyan">▋</Text>
      </Box>
      <Box marginTop={1} paddingX={1}>
        <Text color="#999">Echo: {text || "(empty)"}</Text>
      </Box>
    </Box>
  )
}`,
  },
}

const CATEGORY_CONFIG: Record<string, { color: string; order: number }> = {
  Showcases: { color: "#f9e2af", order: 0 },
  Layout: { color: "#cba6f7", order: 1 },
  Interactive: { color: "#89dceb", order: 2 },
  Runtime: { color: "#a6e3a1", order: 3 },
  Inline: { color: "#fab387", order: 4 },
}

function buildRegistry(): { categories: Category[]; allDemos: DemoEntry[] } {
  const allDemos: DemoEntry[] = []

  for (const [id, component] of Object.entries(SHOWCASES)) {
    const meta = DEMO_METADATA[id]
    if (!meta) continue
    allDemos.push({
      id,
      name: meta.name,
      description: meta.description,
      category: meta.category,
      features: meta.features,
      source: meta.source,
      component: component as () => JSX.Element,
    })
  }

  // Group by category
  const catMap = new Map<string, DemoEntry[]>()
  for (const demo of allDemos) {
    const list = catMap.get(demo.category) ?? []
    list.push(demo)
    catMap.set(demo.category, list)
  }

  const categories: Category[] = []
  for (const [name, items] of catMap) {
    categories.push({
      name,
      color: CATEGORY_CONFIG[name]?.color ?? "#cdd6f4",
      items,
    })
  }
  categories.sort((a, b) => (CATEGORY_CONFIG[a.name]?.order ?? 99) - (CATEGORY_CONFIG[b.name]?.order ?? 99))

  return { categories, allDemos }
}

// =============================================================================
// Syntax Highlighting (CSS class-based)
// =============================================================================

const KW = new Set([
  "import",
  "export",
  "from",
  "function",
  "const",
  "let",
  "var",
  "return",
  "if",
  "else",
  "for",
  "while",
  "switch",
  "case",
  "break",
  "new",
  "typeof",
  "instanceof",
  "async",
  "await",
  "yield",
  "class",
  "extends",
  "interface",
  "type",
  "enum",
  "true",
  "false",
  "null",
  "undefined",
  "as",
  "of",
  "in",
  "default",
  "using",
])

function highlightSource(code: string): string {
  return code
    .split("\n")
    .map((line, i) => {
      const num = `<span class="line-num">${String(i + 1).padStart(3)}</span> `
      const trimmed = line.trimStart()

      // Comment lines
      if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) {
        return num + `<span class="hl-comment">${esc(line)}</span>`
      }

      // Token-by-token highlighting
      let result = ""
      const re =
        /("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`)|(<\/?[A-Z]\w*)|(\b[a-zA-Z_]\w*\b)|(:\s*)([A-Z]\w*)|([^\s"'`<\w]+|\s+)/g
      let m: RegExpExecArray | null
      while ((m = re.exec(line)) !== null) {
        const [full, str, jsxTag, word, colonSpace, typeName] = m
        if (str) {
          result += `<span class="hl-string">${esc(str)}</span>`
        } else if (jsxTag) {
          result += `<span class="hl-jsx">${esc(jsxTag)}</span>`
        } else if (word && KW.has(word)) {
          result += `<span class="hl-keyword">${esc(word)}</span>`
        } else if (colonSpace && typeName) {
          result += `<span class="hl-punct">${esc(colonSpace)}</span><span class="hl-type">${esc(typeName)}</span>`
        } else {
          result += esc(full!)
        }
      }

      return num + result
    })
    .join("\n")
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

// =============================================================================
// DOM Builder
// =============================================================================

function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  attrs?: Record<string, string>,
  ...children: (HTMLElement | string)[]
): HTMLElementTagNameMap[K] {
  const e = document.createElement(tag)
  if (attrs) {
    for (const [k, v] of Object.entries(attrs)) {
      if (k === "className") e.className = v
      else e.setAttribute(k, v)
    }
  }
  for (const child of children) {
    if (typeof child === "string") e.appendChild(document.createTextNode(child))
    else e.appendChild(child)
  }
  return e
}

// =============================================================================
// Main App
// =============================================================================

function createViewerApp(root: HTMLElement): void {
  const { categories, allDemos } = buildRegistry()
  if (allDemos.length === 0) {
    root.textContent = "No demos found."
    return
  }

  let selectedIdx = 0
  let sourceVisible = window.innerWidth >= 900
  let sidebarFocused = false
  let currentInstance: ReturnType<typeof renderToXterm> | null = null

  // ─── Inject styles ─────────────────────────────────────────────────
  const style = document.createElement("style")
  style.textContent = `
    /* Layout */
    #viewer-root { display: flex; flex-direction: column; width: 100%; height: 100%; }
    .vw-header { display: flex; align-items: center; padding: 8px 16px; background: #13132a; border-bottom: 1px solid #313244; min-height: 44px; gap: 12px; }
    .vw-header-brand { font-size: 18px; font-weight: 700; background: linear-gradient(135deg, #cba6f7, #89dceb); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; letter-spacing: -0.5px; }
    .vw-header-title { font-size: 14px; color: #a6adc8; flex-grow: 1; }
    .vw-header-badge { font-size: 12px; color: #89dceb; background: rgba(137, 220, 235, 0.1); padding: 2px 10px; border-radius: 10px; }
    .vw-body { display: flex; flex: 1; overflow: hidden; }

    /* Sidebar */
    .vw-sidebar { width: 220px; min-width: 220px; background: #13132a; border-right: 1px solid #313244; overflow-y: auto; padding: 8px 0; }
    .vw-sidebar::-webkit-scrollbar { width: 4px; }
    .vw-sidebar::-webkit-scrollbar-thumb { background: #45475a; border-radius: 2px; }
    .vw-cat-header { padding: 10px 16px 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.8px; display: flex; align-items: center; gap: 8px; }
    .vw-cat-dot { width: 6px; height: 6px; border-radius: 50%; display: inline-block; }
    .vw-item { padding: 6px 16px 6px 28px; cursor: pointer; font-size: 13px; color: #a6adc8; transition: background 0.1s, color 0.1s; border-left: 2px solid transparent; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .vw-item:hover { background: rgba(137, 220, 235, 0.05); color: #cdd6f4; }
    .vw-item.selected { background: rgba(137, 220, 235, 0.1); color: #89dceb; border-left-color: #89dceb; font-weight: 500; }

    /* Main pane */
    .vw-main { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
    .vw-term-wrap { flex: 1; position: relative; overflow: hidden; padding: 4px; }
    .vw-term-wrap .xterm { height: 100% !important; }
    .vw-info { padding: 12px 16px 8px; border-top: 1px solid #313244; }
    .vw-info-name { font-size: 16px; font-weight: 600; color: #cdd6f4; margin-bottom: 4px; }
    .vw-info-desc { font-size: 13px; color: #a6adc8; margin-bottom: 8px; }
    .vw-badges { display: flex; flex-wrap: wrap; gap: 4px; }
    .vw-badge { font-size: 11px; padding: 1px 8px; border-radius: 8px; background: rgba(137, 180, 250, 0.12); color: #89b4fa; }
    .vw-keyhints { font-size: 11px; color: #6c7086; margin-top: 6px; }
    .vw-keyhints kbd { background: #313244; padding: 1px 5px; border-radius: 3px; font-family: inherit; font-size: 10px; margin: 0 2px; }

    /* Source pane */
    .vw-source { width: 380px; min-width: 380px; background: #11111b; border-left: 1px solid #313244; display: flex; flex-direction: column; overflow: hidden; transition: width 0.2s, min-width 0.2s; }
    .vw-source.hidden { width: 0; min-width: 0; border-left: none; }
    .vw-source-header { display: flex; align-items: center; justify-content: space-between; padding: 8px 12px; border-bottom: 1px solid #313244; }
    .vw-source-title { font-size: 12px; font-weight: 600; color: #a6adc8; text-transform: uppercase; letter-spacing: 0.5px; }
    .vw-source-btn { background: #313244; border: none; color: #a6adc8; font-size: 11px; padding: 3px 10px; border-radius: 4px; cursor: pointer; transition: background 0.15s; }
    .vw-source-btn:hover { background: #45475a; color: #cdd6f4; }
    .vw-source-code { flex: 1; overflow: auto; padding: 8px 0; }
    .vw-source-code::-webkit-scrollbar { width: 4px; }
    .vw-source-code::-webkit-scrollbar-thumb { background: #45475a; border-radius: 2px; }
    .vw-source-code pre { margin: 0; padding: 0 12px; font-family: 'Cascadia Code', 'Fira Code', 'JetBrains Mono', Menlo, monospace; font-size: 12px; line-height: 1.6; color: #cdd6f4; white-space: pre; }
    .line-num { color: #45475a; user-select: none; }
    .hl-comment { color: #6c7086; font-style: italic; }
    .hl-string { color: #a6e3a1; }
    .hl-keyword { color: #cba6f7; }
    .hl-jsx { color: #f9e2af; }
    .hl-type { color: #89dceb; }
    .hl-punct { color: #6c7086; }

    /* Source toggle (small screens) */
    .vw-source-toggle { position: absolute; top: 8px; right: 8px; background: #313244; border: none; color: #a6adc8; font-size: 12px; padding: 4px 10px; border-radius: 4px; cursor: pointer; z-index: 10; display: none; }
    @media (max-width: 900px) {
      .vw-source-toggle { display: block; }
      .vw-source { position: absolute; right: 0; top: 0; bottom: 0; z-index: 20; box-shadow: -4px 0 20px rgba(0,0,0,0.5); }
    }
  `
  document.head.appendChild(style)

  // ─── Build DOM ─────────────────────────────────────────────────────

  // Header
  const header = el(
    "div",
    { className: "vw-header" },
    el("span", { className: "vw-header-brand" }, "hightea"),
    el("span", { className: "vw-header-title" }, "Interactive Examples"),
    el("span", { className: "vw-header-badge" }, `${allDemos.length} demos`),
  )

  // Sidebar
  const sidebar = el("div", { className: "vw-sidebar" })
  const sidebarItems: HTMLElement[] = []

  for (const cat of categories) {
    const catHeader = el("div", { className: "vw-cat-header" })
    const dot = el("span", { className: "vw-cat-dot" })
    dot.style.backgroundColor = cat.color
    catHeader.appendChild(dot)
    catHeader.appendChild(document.createTextNode(cat.name))
    sidebar.appendChild(catHeader)

    for (const demo of cat.items) {
      const idx = allDemos.indexOf(demo)
      const item = el("div", { className: "vw-item" }, demo.name)
      item.dataset.idx = String(idx)
      item.addEventListener("click", () => {
        selectDemo(idx)
        sidebarFocused = true
      })
      sidebar.appendChild(item)
      sidebarItems[idx] = item
    }
  }

  // Terminal pane
  const termWrap = el("div", { className: "vw-term-wrap" })
  const sourceToggle = el("button", { className: "vw-source-toggle" }, "Source")
  termWrap.appendChild(sourceToggle)

  // Info bar
  const infoDiv = el("div", { className: "vw-info" })
  const infoName = el("div", { className: "vw-info-name" })
  const infoDesc = el("div", { className: "vw-info-desc" })
  const badgesDiv = el("div", { className: "vw-badges" })
  const keyHints = el("div", { className: "vw-keyhints" })
  infoDiv.append(infoName, infoDesc, badgesDiv, keyHints)

  // Main pane
  const mainPane = el("div", { className: "vw-main" })
  mainPane.append(termWrap, infoDiv)

  // Source pane
  const sourcePane = el("div", { className: `vw-source${sourceVisible ? "" : " hidden"}` })
  const sourceHeader = el("div", { className: "vw-source-header" })
  const sourceTitle = el("span", { className: "vw-source-title" }, "Source")
  const copyBtn = el("button", { className: "vw-source-btn" }, "Copy")
  sourceHeader.append(sourceTitle, copyBtn)
  const sourceCodeWrap = el("div", { className: "vw-source-code" })
  const sourcePre = el("pre")
  sourceCodeWrap.appendChild(sourcePre)
  sourcePane.append(sourceHeader, sourceCodeWrap)

  // Body
  const body = el("div", { className: "vw-body" })
  body.append(sidebar, mainPane, sourcePane)

  // Root
  root.append(header, body)

  // ─── Terminal setup ────────────────────────────────────────────────
  const term = new Terminal({
    cursorBlink: false,
    convertEol: true,
    cols: 80,
    rows: 24,
    fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', Menlo, monospace",
    fontSize: 14,
    theme: {
      background: "#0f0f1a",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      selectionBackground: "rgba(137, 220, 235, 0.25)",
    },
  })

  const fitAddon = new FitAddon()
  term.loadAddon(fitAddon)
  term.open(termWrap)
  fitAddon.fit()

  // Wire keyboard: when terminal has focus, forward to demo
  term.onData((data) => emitInput(data))

  // Track terminal focus state for showcase cursor/outline
  term.textarea?.addEventListener("focus", () => {
    setTermFocused(true)
    sidebarFocused = false
  })
  term.textarea?.addEventListener("blur", () => {
    setTermFocused(false)
  })

  // Click terminal to focus it (unfocus sidebar)
  termWrap.addEventListener("click", () => {
    sidebarFocused = false
  })

  // ─── Selection logic ───────────────────────────────────────────────
  function selectDemo(idx: number): void {
    if (idx < 0 || idx >= allDemos.length) return
    const prev = selectedIdx
    selectedIdx = idx

    // Update sidebar highlight
    if (sidebarItems[prev]) sidebarItems[prev]!.classList.remove("selected")
    if (sidebarItems[idx]) {
      sidebarItems[idx]!.classList.add("selected")
      sidebarItems[idx]!.scrollIntoView({ block: "nearest" })
    }

    const demo = allDemos[idx]!

    // Update URL hash for deep linking (without triggering hashchange)
    history.replaceState(null, "", `#${demo.id}`)

    // Update info
    infoName.textContent = demo.name
    infoDesc.textContent = demo.description
    badgesDiv.innerHTML = ""
    for (const feat of demo.features) {
      badgesDiv.appendChild(el("span", { className: "vw-badge" }, feat))
    }

    // Key hints based on whether demo has component
    if (demo.component) {
      keyHints.innerHTML =
        "<kbd>j</kbd><kbd>k</kbd> navigate &nbsp; <kbd>Enter</kbd> select &nbsp; <kbd>s</kbd> toggle source &nbsp; Click terminal for keyboard input"
    } else {
      keyHints.innerHTML =
        "<kbd>j</kbd><kbd>k</kbd> navigate &nbsp; <kbd>s</kbd> toggle source &nbsp; Run in terminal: <code>bun run examples/...</code>"
    }

    // Update source pane
    sourcePre.innerHTML = highlightSource(demo.source)

    // Render demo in terminal
    renderDemo(demo)

    // Auto-focus terminal so keyboard input works immediately
    term.focus()
  }

  let pendingRenderFrame: number | null = null

  function renderDemo(demo: DemoEntry): void {
    // Cancel any pending deferred render from a previous switch
    if (pendingRenderFrame !== null) {
      cancelAnimationFrame(pendingRenderFrame)
      pendingRenderFrame = null
    }

    // Cleanup previous — unmount React tree, then fully reset xterm
    if (currentInstance) {
      currentInstance.unmount()
      currentInstance = null
    }
    // Full reset: clear scrollback + visible buffer, reset terminal state
    term.reset()

    // Defer new render by one frame — ensures any pending requestAnimationFrame
    // callbacks from the old demo's render scheduler have fired (and bailed via
    // their unmounted flag), and any queued xterm.write() calls have been processed.
    pendingRenderFrame = requestAnimationFrame(() => {
      pendingRenderFrame = null
      term.reset() // Clean slate after old async work drained

      if (!demo.component) {
        term.writeln("\r\n  This example requires a full terminal runtime.")
        term.writeln(`\r\n  Run: bun run examples/${demo.id}`)
        return
      }

      fitAddon.fit()
      currentInstance = renderToXterm(React.createElement(demo.component), term)
    })
  }

  // ─── Copy button ───────────────────────────────────────────────────
  copyBtn.addEventListener("click", () => {
    const demo = allDemos[selectedIdx]
    if (!demo) return
    void navigator.clipboard.writeText(demo.source).then(() => {
      copyBtn.textContent = "Copied!"
      setTimeout(() => {
        copyBtn.textContent = "Copy"
      }, 1500)
      return undefined
    })
  })

  // ─── Source toggle ─────────────────────────────────────────────────
  function toggleSource(): void {
    sourceVisible = !sourceVisible
    sourcePane.classList.toggle("hidden", !sourceVisible)
    // Refit terminal after layout change
    requestAnimationFrame(() => {
      fitAddon.fit()
      if (currentInstance) currentInstance.refresh()
    })
  }

  sourceToggle.addEventListener("click", toggleSource)

  // ─── Keyboard navigation ──────────────────────────────────────────
  document.addEventListener("keydown", (e: KeyboardEvent) => {
    // Only handle sidebar navigation when sidebar is focused or no terminal focus
    if (sidebarFocused || document.activeElement === document.body) {
      if (e.key === "ArrowDown" || e.key === "j") {
        e.preventDefault()
        selectDemo(Math.min(allDemos.length - 1, selectedIdx + 1))
      } else if (e.key === "ArrowUp" || e.key === "k") {
        e.preventDefault()
        selectDemo(Math.max(0, selectedIdx - 1))
      } else if (e.key === "Enter") {
        e.preventDefault()
        sidebarFocused = false
        term.focus()
      } else if (e.key === "s" || e.key === "S") {
        e.preventDefault()
        toggleSource()
      }
    }
  })

  // Click sidebar to focus it
  sidebar.addEventListener("click", () => {
    sidebarFocused = true
  })

  // ─── Resize handling ───────────────────────────────────────────────
  window.addEventListener("resize", () => {
    fitAddon.fit()
    if (currentInstance) currentInstance.refresh()
  })

  // ─── Initial selection (from URL hash or default) ──────────────────
  const hashId = window.location.hash.slice(1)
  const hashIdx = hashId ? allDemos.findIndex((d) => d.id === hashId) : -1
  selectDemo(hashIdx >= 0 ? hashIdx : 0)

  // Handle browser back/forward navigation
  window.addEventListener("hashchange", () => {
    const id = window.location.hash.slice(1)
    const idx = allDemos.findIndex((d) => d.id === id)
    if (idx >= 0 && idx !== selectedIdx) selectDemo(idx)
  })

  // Signal ready to parent
  window.parent.postMessage({ type: "hightea-ready" }, "*")

  // Expose for debugging
  ;(window as any).highteaViewer = { term, allDemos, selectDemo }
}

// =============================================================================
// Boot
// =============================================================================

const root = document.getElementById("viewer-root")
if (root) {
  createViewerApp(root)
}
