#!/usr/bin/env bun
/**
 * Generate `vendor/silvery/docs/reference/tokens.md` from the canonical
 * `PUBLIC_TOKENS` manifest + a derived Nord theme.
 *
 * Usage:
 *   bun run docs:gen
 *
 * CI guard:
 *   bun run docs:gen && git diff --exit-code docs/reference/tokens.md
 *
 * The generated file is committed (not gitignored) — the diff guard fails
 * any PR that changes a Sterling token without updating the manifest.
 */

import { writeFile, mkdir } from "node:fs/promises"
import { dirname, join } from "node:path"
import { sterling, PUBLIC_TOKENS, FAMILY_ORDER, groupTokensByFamily } from "@silvery/theme/sterling"
import { builtinPalettes } from "@silvery/theme/schemes"
import { checkContrast } from "@silvery/color"
import type { Theme, TokenManifestEntry } from "@silvery/theme/sterling"

const REPO_ROOT = join(import.meta.dir, "..")
const OUT_PATH = join(REPO_ROOT, "docs/reference/tokens.md")

const DOC_PALETTE_NAME = "nord"
const docPalette = builtinPalettes[DOC_PALETTE_NAME]
if (!docPalette) throw new Error(`Token docs require the built-in ${DOC_PALETTE_NAME} palette`)
const docTheme = sterling.deriveFromScheme(docPalette)

function hexOf(theme: Theme, flat: string): string {
  return (theme as unknown as Record<string, string>)[flat] ?? ""
}

function ratioVsSurface(theme: Theme, flat: string): string {
  const fg = hexOf(theme, flat)
  const bg = hexOf(theme, "bg-surface-default")
  const c = checkContrast(fg, bg)
  if (!c) return "—"
  return c.ratio.toFixed(2) + ":1"
}

function familyHeader(name: string): string {
  switch (name) {
    case "default":
      return "Default (canvas)"
    case "surface":
      return "Surface"
    case "border":
      return "Border"
    case "muted":
      return "Muted"
    case "faint":
      return "Faint"
    case "accent":
      return "Accent (link-like, full state matrix)"
    case "info":
      return "Info (status)"
    case "success":
      return "Success (status)"
    case "warning":
      return "Warning (status)"
    case "error":
      return "Error (status)"
    case "selected":
      return "Selected"
    case "inverse":
      return "Inverse"
    case "link":
      return "Link"
    case "cursor":
      return "Cursor"
    case "disabled":
      return "Disabled (neutral)"
    case "backdrop":
      return "Backdrop (modal scrim)"
    default:
      return name
  }
}

function renderFamilyTable(entries: readonly TokenManifestEntry[]): string {
  const rows = entries.map((e) => {
    const hex = hexOf(docTheme, e.flat)
    const ratio = ratioVsSurface(docTheme, e.flat)
    return `| \`${e.flat}\` | \`${hex}\` | ${ratio} | ${e.contrast} | ${e.purpose.replace(/\|/g, "\\|")} | ${e.derivation.replace(/\|/g, "\\|")} | ${e.tierNotes.replace(/\|/g, "\\|")} |`
  })
  return [
    "| Token | Hex (Nord) | Ratio vs canvas | Contract | Purpose | Derivation | Tier notes |",
    "|---|---|---|---|---|---|---|",
    ...rows,
  ].join("\n")
}

function header(): string {
  return `# Sterling tokens — reference

> **Generated.** This file is regenerated by \`bun run docs:gen\` from
> [\`packages/ansi/src/sterling/token-manifest.ts\`](../../packages/ansi/src/sterling/token-manifest.ts).
> Do not edit by hand — your edits will be overwritten.

Sterling is silvery's canonical design system. This page lists every public
flat token, its derivation rule, its contrast guarantee, and how it
degrades under tier quantization. Hex values are computed from the
[\`${DOC_PALETTE_NAME}\`](../../packages/theme/src/schemes/${DOC_PALETTE_NAME}.ts)
palette as a representative example — every Sterling theme has the same
token surface but different hex values.

## Token grammar

Sterling tokens follow **\`[channel]-[role][-state]\`** order (matches Primer
and CSS-var conventions):

- **channel** — \`fg\`, \`bg\`, \`border\`, or \`fg-on\` (text drawn ON a filled
  surface).
- **role** — the semantic family (\`accent\`, \`info\`, \`error\`, \`muted\`, …).
- **state** — optional interaction state (\`hover\`, \`active\`).

Examples:

- \`bg-accent\` — accent fill background.
- \`fg-on-error\` — text color when drawing on \`bg-error\` (button labels, etc.).
- \`bg-info-hover\` — info fill, hover state.
- \`fg-on-inverse-muted\` — deemphasized text on inverse chrome.
- \`border-focus\` — focus-ring border.

## Decision tree

1. **Drawing text on the unstyled canvas?** → use \`fg-default\` (or omit).
2. **Drawing text on a filled colored surface?** → use \`fg-on-<role>\`.
3. **Status (info / success / warning / error)?** → status family.
4. **Action emphasis (default / primary / destructive)?** → use the component's
   \`variant\` prop, NOT a separate token role. \`destructive\` is a
   component-layer alias to \`error\` — Sterling has no \`bg-destructive\`.
5. **Disabled state?** → \`disabled\` family. Disabled is **neutral** —
   sourced from base interface tokens, not from \`error\`/\`success\`/etc.
6. **Modal scrim?** → \`bg-backdrop\` (NOT \`bg-surface-overlay\`, which is the
   popover/tooltip card bg).

## Family capability matrix

Not every family supports every channel — the asymmetry is intentional and
type-enforced. Status roles do not support \`fg.hover\` / \`fg.active\` because
text on a status (e.g. \`fg-error\`) is a label, not an interactive link.

| Family | fg | bg | fgOn | border | hover.fg | hover.bg | active.fg | active.bg | muted.fgOn |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| accent | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | – |
| info / success / warning / error (status) | ✓ | ✓ | ✓ | – | – | ✓ | – | ✓ | – |
| muted | ✓ | ✓ | – | – | – | – | – | – | – |
| faint | ✓ | – | – | – | – | – | – | – | – |
| surface | – | ✓ | – | – | – | ✓ | – | – | – |
| border | – | – | – | ✓ | – | – | – | – | – |
| cursor | ✓ | ✓ | – | – | – | – | – | – | – |
| selected | – | ✓ | ✓ | – | – | ✓ | – | – | – |
| inverse | – | ✓ | ✓ | – | – | ✓ | – | – | ✓ |
| link | ✓ | – | – | – | ✓ | – | – | – | – |
| disabled | ✓ | ✓ | – | ✓ | – | – | – | – | – |
| backdrop | – | ✓ | – | – | – | – | – | – | – |
| default | ✓ | ✓ | – | – | – | – | – | – | – |

## Asymmetric Surprise principle

Sterling tokens are designed so adopters never get \`undefined\` from a
reasonable lookup. Every flat key in this page exists on every derived
Theme. The compiler refuses \`<Alert variant="destructive">\` (Alert doesn't
accept that variant); dynamic indexing of unknown tokens throws a
\`TypeError\` with a "did you mean…?" hint. The guarantee is asymmetric by
design: known keys are total across derived themes, while unknown keys fail
loudly.

## Tokens by family

`
}

async function main(): Promise<void> {
  const grouped = groupTokensByFamily()
  const sections: string[] = []
  for (const family of FAMILY_ORDER) {
    const entries = grouped.get(family)
    if (!entries || entries.length === 0) continue
    sections.push(`### ${familyHeader(family)}\n\n${renderFamilyTable(entries)}\n`)
  }

  const ratioVsCanvas = `\`bg-surface-default\` (= \`#${hexOf(docTheme, "bg-surface-default").replace(/^#/, "")}\` for Nord)`
  const trailer = `

## See also

- [\`STERLING_FLAT_TOKENS\`](../../packages/ansi/src/sterling/flat-tokens.ts) — the type-level union, in lockstep with this page
- [\`PUBLIC_TOKENS\`](../../packages/ansi/src/sterling/token-manifest.ts) — the manifest powering this generator
- "Ratio vs canvas" measures contrast against ${ratioVsCanvas}; surface and border values are listed for reference only. Text-token guarantees are stated explicitly in the Contract column (deemphasized text may intentionally sit below AA).
`

  const md = header() + sections.join("\n") + trailer

  await mkdir(dirname(OUT_PATH), { recursive: true })
  await writeFile(OUT_PATH, md, "utf8")
  console.log(`Wrote ${OUT_PATH}`)
  console.log(`  ${PUBLIC_TOKENS.length} tokens across ${grouped.size} families`)
  console.log(`  ${md.split("\n").length} lines, ${md.length} bytes`)
}

await main()
