/** Retired token spellings and the channel-aware canonical cure for each. */
export const LEGACY_THEME_TOKEN_CURES: Readonly<Record<string, string>> = {
  primary: '"$fg-accent" for text or "$bg-accent" for fills',
  "primary-hover": '"$fg-accent-hover" for text or "$bg-accent-hover" for fills',
  "primary-active": '"$fg-accent-active" for text or "$bg-accent-active" for fills',
  primaryfg: '"$fg-on-accent"',
  secondary: '"$fg-link" for navigation or "$purple" for a categorical hue',
  secondaryfg: '"$fg-on-accent" only for an actual accent fill',
  accent: '"$fg-accent" for text or "$bg-accent" for fills',
  "accent-hover": '"$fg-accent-hover" for text or "$bg-accent-hover" for fills',
  "accent-active": '"$fg-accent-active" for text or "$bg-accent-active" for fills',
  accentfg: '"$fg-on-accent"',
  "accent-fg":
    '"$fg-accent" for accent-colored text or "$fg-on-accent" for text on an accent background',
  muted: '"$fg-muted"',
  mutedbg: '"$bg-muted"',
  surface: '"$fg" for text or "$bg-surface-raised" for fills',
  surfacebg: '"$bg-surface-raised"',
  "surface-bg": '"$bg-surface-raised"',
  popover: '"$fg" for text or "$bg-surface-overlay" for fills',
  popoverbg: '"$bg-surface-overlay"',
  "popover-bg": '"$bg-surface-overlay"',
  error: '"$fg-error" for text or "$bg-error" for fills',
  errorfg: '"$fg-on-error"',
  warning: '"$fg-warning" for text or "$bg-warning" for fills',
  warningfg: '"$fg-on-warning"',
  "warning-fg":
    '"$fg-warning" for warning-colored text or "$fg-on-warning" for text on a warning background',
  success: '"$fg-success" for text or "$bg-success" for fills',
  successfg: '"$fg-on-success"',
  info: '"$fg-info" for text or "$bg-info" for fills',
  infofg: '"$fg-on-info"',
  border: '"$border-default"',
  inputborder: '"$border-default"',
  focusborder: '"$border-focus"',
  "focus-border": '"$border-focus"',
  "bg-surface": '"$bg-surface-default"',
  "bg-popover": '"$bg-surface-overlay"',
  "fg-selected": '"$fg-on-selected"',
  "border-input": '"$border-default"',
  "fg-on-primary": '"$fg-on-accent"',
  cursor: '"$fg-cursor" for text or "$bg-cursor" for fills',
  cursorbg: '"$bg-cursor"',
  "cursor-bg": '"$bg-cursor"',
  selection: '"$fg-on-selected"',
  selectionbg: '"$bg-selected"',
  inverse: '"$fg-on-inverse"',
  inversebg: '"$bg-inverse"',
  link: '"$fg-link"',
  disabledfg: '"$fg-disabled"',
}
